### ISSUE TITLE
ball_dodgeball

### ISSUE THREAD

**Issue by kevATin** [biell/alti-maps#2]
"ball_dodgeball" isn't included in this archive, same with it's plus.txt.
Is this on purpose?

**Comment by biell** [comment]
I didn't make ball_dodgeball, that is why.  This only has the games I either created or modified.  I think Van created the ball_dodgeball map.  Also, because of that, ball_dodgeball doesn't have a plus.txt file included, that is my own invention and only works on alti+server maps.

Van created a special server just for ball_dodgeball, then he wrote a bespoke wrapper to manage the ball_dodgeball game.

I realized that adding ball_dodgeball to an alti+ server wouldn't actually be that much work.

The alti+ settings (what would go in the plus.txt file) are listed in the script, they are:
```
  /add plane Loopy,Acid
  /add plane Bomber
  /add plane Biplane
  /set botCount 0
```
Which restricts the planes and turns off bots.

The rest of it is in the script.  I think ball_dodgeball is a great example of how you can extend an alti+ server if you are OK with writing perl code.  It shows how simple it is to add a few new HOOKS and make a game possible without having to worry about the minutia of dealing with how to read and write from the log files and provide the basic services necessary to make an altitude wrapper.

It uses the server, player, map, queue, tourney, and chat packages to do the heavy lifting and make the code simpler and easier to read.  It provides a good example of how to initialize a map on the mapChange event.  There is an example of adding your own `game` routine to add a `/game ...` game specific command.  And it shows how to pin actions to the 'pingSummary' event which happens every couple seconds.

**Comment by kevATin** [comment]
> This only has the games I either created or modified.

Ah i see; given it's size I had assumed a more general inclusion approach.

> Van created a special server just for ball_dodgeball, then he wrote a bespoke wrapper to manage the ball_dodgeball game.

Fascinating that such a small game as Altitude already had multiple custom server softwares.

> The alti+ settings (what would go in the plus.txt file) are listed in the script, they are:

Yep, I had already found that info on http://altiplus.glaciated.org/maps:ball_dodgeball

Any reason why on glaciated "/set gravity 2" is included to make the ball gravity-less, and not in the suggested settings on the ball_dodgeball script?

> I think ball_dodgeball is a great example of how you can extend an alti+ server if you are OK with writing perl code.

I dug through all the example-scripts yesterday and tried to understand them. I think I got the general idea, but I'll need to read up on perl sometime soon~

> It uses the server, player, map, queue, tourney, and chat packages to do the heavy lifting and make the code simpler and easier to read.

Yeah I'll have to read through those too~

Edit: formatting

**Comment by biell** [comment]
Altitude is pretty old, it was once a huge game, before Rocket League came out and everyone jumped ship.  I wouldn't say it was as big as Rocket League, but it was flourishing for a few years.

I think Van didn't have ball gravity set to 2, but I think the map works better.  I think that is why there is the difference.

I think a lot of people would have preferred if I wrote my code in python, but it is hard to teach this old dog new tricks.  Perl is just easier for me, I am a system administrator by trade, so that was our go-to language for 20+ years.

**Comment by kevATin** [comment]
I bought the game on steam at the end of 2011, and I'm pretty sure I played the demo before that for a while. Can't remember how active it was, and I didn't pay too much attention to the game in general other than spending some time playing every once in a while. I think I had a bigger pause of more than a year sometime after that, and multiple shorter ones in between~
I did see players talking a lot about Rocket League when it came out, so that checks out.
